# Generated by Django 5.1.1 on 2024-09-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'verbose_name': 'اطلاعات فایل', 'verbose_name_plural': 'اطلاعات فایل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='filerecord',
            options={'permissions': [('can_edit_file_record', 'ویرایش فایل\u200cها')], 'verbose_name': 'رکورد فایل', 'verbose_name_plural': 'رکورد های فایل'},
        ),
    ]
