# Generated by Django 5.1.1 on 2024-09-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fileinfo_options_alter_filerecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileinfo',
            options={'verbose_name': 'مشخصات', 'verbose_name_plural': 'مشخصات'},
        ),
        migrations.AlterModelOptions(
            name='filerecord',
            options={'permissions': [('can_edit_file_record', 'ویرایش فایل\u200cها')], 'verbose_name': 'کارتکس', 'verbose_name_plural': 'کارتکس ها'},
        ),
    ]
