# Generated by Django 5.1.1 on 2024-09-23 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fileinfo_options_alter_filerecord_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=100, verbose_name='کد فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فایل')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('creator', models.CharField(max_length=100, verbose_name='ثبت کننده')),
                ('user_code', models.CharField(max_length=100, verbose_name='کد کاربر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارتکس',
                'verbose_name_plural': 'کارتکس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200, verbose_name='نام مالک')),
                ('ownership_start_date', models.DateField(verbose_name='تاریخ شروع مالکیت')),
                ('ownership_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان مالکیت')),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد سهم')),
            ],
            options={
                'verbose_name': 'مالکیت',
                'verbose_name_plural': 'مالکیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر ملک',
                'verbose_name_plural': 'تصاویر ملک',
            },
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('images', models.ManyToManyField(blank=True, to='app.propertyimage', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'موقعیت ملک',
                'verbose_name_plural': 'موقعیت\u200cهای ملک',
            },
        ),
        migrations.CreateModel(
            name='PropertySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('building', 'ساختمان'), ('apartment', 'آپارتمان'), ('villa', 'ویلایی'), ('land', 'زمین'), ('garden', 'باغ'), ('old_building', 'کلنگی')], max_length=20, verbose_name='نوع ملک')),
                ('floor_number', models.IntegerField(blank=True, null=True, verbose_name='شماره طبقه')),
                ('units_per_floor', models.IntegerField(blank=True, null=True, verbose_name='تعداد واحدهای هر طبقه')),
                ('usage', models.CharField(blank=True, choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('administrative', 'اداری'), ('educational', 'آموزشی'), ('industrial', 'صنعتی')], max_length=200, verbose_name='کاربری')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت (مترمربع)')),
                ('position', models.CharField(choices=[('north', 'شمالی'), ('south', 'جنوبی'), ('east', 'شرقی'), ('west', 'غربی')], max_length=20, verbose_name='موقعیت')),
                ('corner_position', models.CharField(choices=[('one_corner', 'یک کله'), ('two_corners', 'دو کله'), ('two_side', 'دو نبش'), ('three_side', 'سه نبش'), ('four_side', 'چهار نبش')], max_length=20, verbose_name='موقعیت نبش')),
            ],
            options={
                'verbose_name': 'مشخصات ملک',
                'verbose_name_plural': 'مشخصات ملک\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, verbose_name='شماره ثبت')),
                ('registration_date', models.DateField(verbose_name='تاریخ ثبت')),
                ('registration_authority', models.CharField(max_length=200, verbose_name='مرجع ثبت')),
                ('employee_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cartext', verbose_name='کارتکس')),
            ],
            options={
                'verbose_name': 'اطلاعات ثبتی',
                'verbose_name_plural': 'اطلاعات ثبتی',
            },
        ),
        migrations.CreateModel(
            name='TechnicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(verbose_name='مهارت\u200cها')),
                ('certifications', models.TextField(verbose_name='گواهی\u200cنامه\u200cها')),
                ('technical_experience', models.TextField(verbose_name='تجربه فنی')),
                ('employee_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cartext', verbose_name='کارتکس')),
            ],
            options={
                'verbose_name': 'اطلاعات فنی',
                'verbose_name_plural': 'اطلاعات فنی',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100, verbose_name='نوع معامله')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('transaction_date', models.DateField(verbose_name='تاریخ معامله')),
                ('employee_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cartext', verbose_name='کارتکس')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(max_length=100, verbose_name='نوع انشعاب')),
                ('utility_details', models.CharField(max_length=200, verbose_name='جزئیات انشعاب')),
                ('employee_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cartext', verbose_name='کارتکس')),
            ],
            options={
                'verbose_name': 'انشعاب',
                'verbose_name_plural': 'انشعابات',
            },
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
        migrations.DeleteModel(
            name='FileRecord',
        ),
    ]
