# Generated by Django 5.1.1 on 2024-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cartext_ownership_propertyimage_propertylocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='contact_number',
            field=models.CharField(default=0, max_length=15, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='mobile_number',
            field=models.CharField(default=0, max_length=15, verbose_name='شماره همراه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='national_id',
            field=models.CharField(default=0, max_length=10, verbose_name='کد ملی / شناسه ملی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='person_type',
            field=models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default=0, max_length=10, verbose_name='نوع شخصیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownership',
            name='share_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='سهم از ملک (دانگ)'),
        ),
    ]
